config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'todos', to: 'todos#index'
  post 'todos', to: 'todos#create'

  get 'todos/new'

  get 'todos/list'

  get 'todos/:id', to: 'todos#show', as: 'todo'

  get 'todos/:id/edit', to: 'todos#edit', as:'edit_todo'

  patch 'todos/:id', to: 'todos#update'

  delete 'todos/:id', to: 'todos#destroy', as:'destroy_todo'

  get 'todos/:id/complete', to: 'todos#complete', as:'complete_todo'



  root 'todos#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    todo = Todo.new(todo_params)
    todo.save
      redirect_to todos_path, notice: 'Se creo la tarea con exito!'
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path, notice: "Se actualizo ToDo con exito"
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path, notice: "Se elimino ToDo con exito"
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to todos_path, notice: "Se completo ToDo con exito"
  end

  def list
    @todos = Todo.all

  end


  private

  def todo_params
    params.require(:todo).permit(:description, :completed)

  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="<%= todos_path %>">Index</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= todos_list_path %>">List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= todos_new_path %>">New</a>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>EDIT</h1>
<br><br>

<%= form_with(model: @todo, local: true) do |form| %>

<%= form.label :description %>
<%= form.text_field :description %>

<%= form.label :completed %>
<%= form.check_box :completed %>

<br><br>

<%= form.submit 'Actualizar'%>
<br><br>
<%= link_to 'Crear ToDo', root_path %>


<% end %>

app/views/todos/index.html.erb
<h1>INDEX</h1>

<% notice %>

<div class="card" style="width: 18rem;">
    <% @todos.each do |todo| %>
  <div class="card-body">

    <h5 class="card-title"><%= todo.description %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= todo.description %></h6>
    <%= link_to 'Marcar como Completado', complete_todo_path(todo)  %>
    <br>
    <%= link_to 'Mostrar', todo_path(todo)  %>
    <br>
    <%= link_to 'Editar', edit_todo_path(todo)  %>
    <br>
    <%= link_to 'Eliminar', destroy_todo_path(todo)  %>
    <br>
    <%= todo.completed %>
  </div>

  <% end %>
</div>

<%= link_to 'Crear ToDo', todos_new_path %>

app/views/todos/list.html.erb
<h1>LIST</h1>
<%= notice %>

<% @todos.each do |todo| %>
<div class="container">
  <div table="col-md-6">
        <%= todo.completed %>
  </div>



    <div table="col-md-6">
          <%= todo.completed %>
          Lorem ipsum dolor sit amet
  </div>
</div>

<% end %>

app/views/todos/new.html.erb
<h1>FORMULARIO</h1>
<br><br>
<% notice %>



<br><br>



<%= form_with(model: @todo, local: true) do |form| %>

<%= form.label :description %>
<%= form.text_field :description %>

<!-- <%= form.label :completed %>
<%= form.check_box :completed %> -->

<br><br>

<%= form.submit 'Crear ToDo'%>
<br><br>



<% end %>

app/views/todos/show.html.erb
<h1>SHOW</h1>
<br><br>

<p>
<strong>Description:</strong> <%= @todo.description  %>
</p>

<p>
<strong>Completed ???</strong> <%= @todo.completed  %>
</p>